# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hammertime}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Avdi Grimm"]
  s.date = %q{2010-01-17}
  s.description = %q{When this library is required, it replaces the default Ruby exception-raising
behavior.  When an error is raised, the developer is presented with a menu
enabling them to ignore the error, view a stack trace, debug the error using IRB
or ruby-debug, and more.
}
  s.email = %q{avdi@avdi.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "example.rb",
     "lib/hammertime.rb",
     "spec/hammertime_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/avdi/hammertime}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Exception debugging console for Ruby}
  s.test_files = [
    "spec/hammertime_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-debug>, ["~> 0.10"])
      s.add_runtime_dependency(%q<highline>, ["~> 1.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
      s.add_dependency(%q<highline>, ["~> 1.5"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
    s.add_dependency(%q<highline>, ["~> 1.5"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

