# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "hammertime"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Avdi Grimm"]
  s.date = "2012-01-30"
  s.description = "When this library is required, it replaces the default Ruby exception-raising\nbehavior.  When an error is raised, the developer is presented with a menu\nenabling them to ignore the error, view a stack trace, debug the error using IRB\nor ruby-debug, and more.\n"
  s.email = "avdi@avdi.org"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "example.rb",
    "examples/loaderror.rb",
    "hammertime.gemspec",
    "lib/hammertime.rb",
    "spec/hammertime_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/avdi/hammertime"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Exception debugging console for Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ruby-debug>, ["~> 0.10"])
      s.add_runtime_dependency(%q<highline>, ["~> 1.5"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
      s.add_dependency(%q<highline>, ["~> 1.5"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<ruby-debug>, ["~> 0.10"])
    s.add_dependency(%q<highline>, ["~> 1.5"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

